name: emart

on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: build
        run: npm run build
